//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neptuo.Productivity.SolutionRunner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SourceDirectoryPath {
            get {
                return ((string)(this["SourceDirectoryPath"]));
            }
            set {
                this["SourceDirectoryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreferedApplicationPath {
            get {
                return ((string)(this["PreferedApplicationPath"]));
            }
            set {
                this["PreferedApplicationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PinnedFiles {
            get {
                return ((string)(this["PinnedFiles"]));
            }
            set {
                this["PinnedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RunKey {
            get {
                return ((string)(this["RunKey"]));
            }
            set {
                this["RunKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSearchMode {
            get {
                return ((string)(this["FileSearchMode"]));
            }
            set {
                this["FileSearchMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FileSearchCount {
            get {
                return ((int)(this["FileSearchCount"]));
            }
            set {
                this["FileSearchCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSearchPattern {
            get {
                return ((string)(this["FileSearchPattern"]));
            }
            set {
                this["FileSearchPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFileSearchPatternSaved {
            get {
                return ((bool)(this["IsFileSearchPatternSaved"]));
            }
            set {
                this["IsFileSearchPatternSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLastUsedApplicationSavedAsPrefered {
            get {
                return ((bool)(this["IsLastUsedApplicationSavedAsPrefered"]));
            }
            set {
                this["IsLastUsedApplicationSavedAsPrefered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDismissedWhenLostFocus {
            get {
                return ((bool)(this["IsDismissedWhenLostFocus"]));
            }
            set {
                this["IsDismissedWhenLostFocus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsHiddentOnStartup {
            get {
                return ((bool)(this["IsHiddentOnStartup"]));
            }
            set {
                this["IsHiddentOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdditionalApplications {
            get {
                return ((string)(this["AdditionalApplications"]));
            }
            set {
                this["AdditionalApplications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoSelectApplicationVersion {
            get {
                return ((bool)(this["IsAutoSelectApplicationVersion"]));
            }
            set {
                this["IsAutoSelectApplicationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFileNameRemovedFromDisplayedPath {
            get {
                return ((bool)(this["IsFileNameRemovedFromDisplayedPath"]));
            }
            set {
                this["IsFileNameRemovedFromDisplayedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDisplayedPathTrimmedToLastFolderName {
            get {
                return ((bool)(this["IsDisplayedPathTrimmedToLastFolderName"]));
            }
            set {
                this["IsDisplayedPathTrimmedToLastFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTrayIcon {
            get {
                return ((bool)(this["IsTrayIcon"]));
            }
            set {
                this["IsTrayIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsStatisticsCounted {
            get {
                return ((bool)(this["IsStatisticsCounted"]));
            }
            set {
                this["IsStatisticsCounted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CenterPrimaryScreen")]
        public global::Neptuo.Productivity.SolutionRunner.Services.Positions.PositionMode PositionMode {
            get {
                return ((global::Neptuo.Productivity.SolutionRunner.Services.Positions.PositionMode)(this["PositionMode"]));
            }
            set {
                this["PositionMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PositionLeft {
            get {
                return ((double)(this["PositionLeft"]));
            }
            set {
                this["PositionLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PositionTop {
            get {
                return ((double)(this["PositionTop"]));
            }
            set {
                this["PositionTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HiddenMainApplications {
            get {
                return ((string)(this["HiddenMainApplications"]));
            }
            set {
                this["HiddenMainApplications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoSelectApplicationMinimalVersion {
            get {
                return ((string)(this["AutoSelectApplicationMinimalVersion"]));
            }
            set {
                this["AutoSelectApplicationMinimalVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dark")]
        public global::Neptuo.Productivity.SolutionRunner.Services.Themes.ThemeMode ThemeMode {
            get {
                return ((global::Neptuo.Productivity.SolutionRunner.Services.Themes.ThemeMode)(this["ThemeMode"]));
            }
            set {
                this["ThemeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsProjectCountEnabled {
            get {
                return ((bool)(this["IsProjectCountEnabled"]));
            }
            set {
                this["IsProjectCountEnabled"] = value;
            }
        }
    }
}
